dist: bionic
language: csharp
dotnet: "3.1"
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

install:
  - dotnet tool restore
  - dotnet paket install
  - dotnet restore

script:
 - dotnet build
 - dotnet test
